### ISSUE TITLE
Bad `treatments.yml` fails silently

### ISSUE THREAD

**Issue by JamesPHoughton** [empiricaly/empirica#116]
We've noticed that if your project has an improperly formatted `treatments.yml` file, Empirica V2 will just skip using it without raising any warnings. It's not a big problem, but it would be helpful to have an informative feedback message.

**Comment by JamesPHoughton** [comment]
Interestingly, if you have already run a batch, and you break the `treatments.yml`, you can still duplicate an old batch and run it.

**Comment by npaton** [comment]
Treatments are copied into the batch, so they are not affected by changes to the `treatments.yaml` file.

I agree we should validate the `treatments.yaml` file at startup and log a warning. 👍

**Comment by JamesPHoughton** [comment]
On further reflection, the validation should probably be mostly just a yml parser validation. We're starting to abuse the original intent of the independent treatments in really interesting ways. Here's a treatment from my most recent .yml

```yml
- name: demo1p
    desc: Demo listening study (13 min video)
    factors:
      playerCount: 1
      gameStages:
        - name: Stars Video
          type: video
          url: https://youtu.be/QC8iQqtG0hg
        - name: multipleChoicePrompt
          type: prompt
          prompt: example/multipleChoice.md
          duration: 6000
        - name: Speaking Video
          type: video
          url: https://youtu.be/2cNP2r2lrLU
        - name: icebreaker
          type: discussion
          prompt: example/openResponse.md
          duration: 30000
        - name: deliberation
          type: discussion
          prompt: anes2020/worry_less_abt_equality.md
          duration: 30000
      exitSurveys:
        - LonelinessSingleItem
        - ListeningQualityPartner
        - Demographics

```
We're strongly taking advantage of the fact that the treatment is just copied to the game, and making factors contain lists and objects, etc. It's quite different from the original intent of each factor being a single `key:value` pair, but is very convenient.  (It also makes the `factors` section of the `treatments.yaml` completely impossible, but hey... 🤓
